### ISSUE TITLE
Return values for stubs

### ISSUE THREAD

**Issue by marcel-suter-bzz** [templates-python/m319-lu20-a01-library#3]
Change return values for

- read_int: return minimum 
- read_date: return datetime.now()

**Comment by graphics80** [comment]
Ich möchte eben dass der Dialog im main() funktioniert, deshalb der read_int mit input.

readDate ohne inhalt, damit import datetime nicht bereits erledigt ist...

Was meinst du @marcel-suter-bzz

**Comment by marcel-suter-bzz** [comment]
Der Dialog funktioniert grundsätzlich, es wird halt immer das Minimum zurück gegeben.

Bei read_date würde ich dann zumindest "return None" machen.

**Comment by graphics80** [comment]
Dialog läuft aber ohne Pause...

read_date passe ich an.
